# Heart Disease Dataset

# Description

## Part 1 - Data Preprocessing

### Importing the dataset

In [32]:
import pandas as pd
import numpy as np

dataset = pd.read_csv('heartdisease-UCI.csv')

In [33]:
dataset

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0      52    1   0       125   212    0        1      168      0      1.0   
1      53    1   0       140   203    1        0      155      1      3.1   
2      70    1   0       145   174    0        1      125      1      2.6   
3      61    1   0       148   203    0        1      161      0      0.0   
4      62    0   0       138   294    1        1      106      0      1.9   
...   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
1020   59    1   1       140   221    0        1      164      1      0.0   
1021   60    1   0       125   258    0        0      141      1      2.8   
1022   47    1   0       110   275    0        0      118      1      1.0   
1023   50    0   0       110   254    0        0      159      0      0.0   
1024   54    1   0       120   188    0        1      113      0      1.4   

      slope  ca  thal  target  
0         2   2     3       0  
1         0   0     3       0  
2         0   0     3       0  
3         2   1     3       0  
4         1   3     2       0  
...     ...  ..   ...     ...  
1020      2   0     2       1  
1021      1   1     3       0  
1022      1   1     2       0  
1023      2   0     2       1  
1024      1   1     3       0  

[1025 rows x 14 columns]

### Data Cleaning

In [34]:
dataset = dataset.drop_duplicates()

dataset

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     52    1   0       125   212    0        1      168      0      1.0   
1     53    1   0       140   203    1        0      155      1      3.1   
2     70    1   0       145   174    0        1      125      1      2.6   
3     61    1   0       148   203    0        1      161      0      0.0   
4     62    0   0       138   294    1        1      106      0      1.9   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
723   68    0   2       120   211    0        0      115      0      1.5   
733   44    0   2       108   141    0        1      175      0      0.6   
739   52    1   0       128   255    0        1      161      1      0.0   
843   59    1   3       160   273    0        0      125      0      0.0   
878   54    1   0       120   188    0        1      113      0      1.4   

     slope  ca  thal  target  
0        2   2     3       0  
1        0   0     3       0  
2        0   0     3       0  
3        2   1     3       0  
4        1   3     2       0  
..     ...  ..   ...     ...  
723      1   0     2       1  
733      1   0     2       1  
739      2   1     3       0  
843      2   0     2       0  
878      1   1     3       0  

[302 rows x 14 columns]

In [35]:
dataset['target'] = np.where(dataset['target'] <= 1, 0, dataset['target'])
dataset['target'] = np.where(dataset['target'] > 0, 1, dataset['target'])

dataset

C:\Users\jolyn\AppData\Local\Temp\ipykernel_23820\2560074617.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset['target'] = np.where(dataset['target'] <= 1, 0, dataset['target'])
C:\Users\jolyn\AppData\Local\Temp\ipykernel_23820\2560074617.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset['target'] = np.where(dataset['target'] > 0, 1, dataset['target'])


age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     52    1   0       125   212    0        1      168      0      1.0   
1     53    1   0       140   203    1        0      155      1      3.1   
2     70    1   0       145   174    0        1      125      1      2.6   
3     61    1   0       148   203    0        1      161      0      0.0   
4     62    0   0       138   294    1        1      106      0      1.9   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
723   68    0   2       120   211    0        0      115      0      1.5   
733   44    0   2       108   141    0        1      175      0      0.6   
739   52    1   0       128   255    0        1      161      1      0.0   
843   59    1   3       160   273    0        0      125      0      0.0   
878   54    1   0       120   188    0        1      113      0      1.4   

     slope  ca  thal  target  
0        2   2     3       0  
1        0   0     3       0  
2        0   0     3       0  
3        2   1     3       0  
4        1   3     2       0  
..     ...  ..   ...     ...  
723      1   0     2       0  
733      1   0     2       0  
739      2   1     3       0  
843      2   0     2       0  
878      1   1     3       0  

[302 rows x 14 columns]

### Getting the Inputs and Outputs of the System

In [36]:
X = dataset.iloc[:, :-1].values

X

array([[52.,  1.,  0., ...,  2.,  2.,  3.],
       [53.,  1.,  0., ...,  0.,  0.,  3.],
       [70.,  1.,  0., ...,  0.,  0.,  3.],
       ...,
       [52.,  1.,  0., ...,  2.,  1.,  3.],
       [59.,  1.,  3., ...,  2.,  0.,  2.],
       [54.,  1.,  0., ...,  1.,  1.,  3.]])

In [37]:
Y = dataset.iloc[:, -1].values

Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

### Creating the Training Set and the Test Set

In [38]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_test, Y_train = train_test_split(X, Y, test_size=0.2)

In [39]:
X_train

array([[56.,  0.,  1., ...,  1.,  0.,  2.],
       [54.,  0.,  2., ...,  2.,  0.,  2.],
       [64.,  0.,  0., ...,  1.,  2.,  2.],
       ...,
       [37.,  0.,  2., ...,  2.,  0.,  2.],
       [68.,  1.,  2., ...,  2.,  1.,  3.],
       [58.,  0.,  0., ...,  1.,  0.,  2.]])

In [40]:
X_test

array([[5.00e+01, 0.00e+00, 0.00e+00, 1.10e+02, 2.54e+02, 0.00e+00,
        0.00e+00, 1.59e+02, 0.00e+00, 0.00e+00, 2.00e+00, 0.00e+00,
        2.00e+00],
       [4.00e+01, 1.00e+00, 0.00e+00, 1.10e+02, 1.67e+02, 0.00e+00,
        0.00e+00, 1.14e+02, 1.00e+00, 2.00e+00, 1.00e+00, 0.00e+00,
        3.00e+00],
       [4.30e+01, 1.00e+00, 0.00e+00, 1.20e+02, 1.77e+02, 0.00e+00,
        0.00e+00, 1.20e+02, 1.00e+00, 2.50e+00, 1.00e+00, 0.00e+00,
        3.00e+00],
       [4.50e+01, 0.00e+00, 0.00e+00, 1.38e+02, 2.36e+02, 0.00e+00,
        0.00e+00, 1.52e+02, 1.00e+00, 2.00e-01, 1.00e+00, 0.00e+00,
        2.00e+00],
       [6.40e+01, 1.00e+00, 2.00e+00, 1.40e+02, 3.35e+02, 0.00e+00,
        1.00e+00, 1.58e+02, 0.00e+00, 0.00e+00, 2.00e+00, 0.00e+00,
        2.00e+00],
       [4.20e+01, 0.00e+00, 0.00e+00, 1.02e+02, 2.65e+02, 0.00e+00,
        0.00e+00, 1.22e+02, 0.00e+00, 6.00e-01, 1.00e+00, 0.00e+00,
        2.00e+00],
       [5.40e+01, 0.00e+00, 2.00e+00, 1.35e+02, 3.04e+02, 1.00e+00,
  

In [41]:
Y_test

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [43]:
Y_train

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Feature Scaling

In [65]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

X_train = sc.fit_transform(X_train)

## Part 2 - Building and training the model

### Building the model

In [66]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(random_state = 0)

### Training the model

In [69]:
model.fit(X_train, Y_train)

ValueError: Found input variables with inconsistent numbers of samples: [241, 61]

### Inference

Making the predictons of the data points in the test set

In [16]:
y_pred = model.predict(sc.transform(X_test))

In [17]:
y_pred

array([2, 2, 4, 4, 2, 2, 2, 4, 2, 2, 4, 2, 4, 2, 2, 2, 4, 4, 4, 2, 2, 2,
       4, 2, 4, 4, 2, 2, 2, 4, 2, 4, 4, 2, 2, 2, 4, 4, 2, 4, 2, 2, 2, 2,
       2, 2, 2, 4, 2, 2, 4, 2, 4, 2, 2, 2, 4, 4, 2, 4, 2, 2, 2, 2, 2, 2,
       2, 2, 4, 4, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 4, 2, 4, 2, 2, 4, 2, 4,
       4, 2, 4, 2, 4, 4, 2, 4, 4, 4, 4, 2, 2, 2, 4, 4, 2, 2, 4, 2, 2, 2,
       4, 2, 2, 4, 2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 4, 4, 2, 4, 2, 4, 2, 2,
       4, 2, 2, 4, 2], dtype=int64)

Making the prediction of a single data point with:

1. Sample Code Number = 1000000
2. Clump Thickness = 1
3. Uniformity of Cell Size = 2
4. Uniformity of Cell Shape = 3
5. Marginal Adhesion = 4
6. Single Epithelial Cell Size = 5
7. Bare Nuclei = 6
8. Bland Chromatin = 7
9. Normal Nucleoli = 8
10. Mitoses = 9

In [18]:
model.predict(sc.transform([[1,2,3,4,5,6,7,8,9]]))

array([4], dtype=int64)

## Part 3: Evaluating the model 

### Confusion Matrix

In [19]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[84,  3],
       [ 3, 47]], dtype=int64)

### Accuracy

In [20]:
(84+47)/(84+47+3+3)

0.9562043795620438

In [21]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9562043795620438